### PR TITLE
Added a contrib script that easies its starting up and checking if it works

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by zhsj** [comment]
Sorry, but I don't want a Python script.

**Comment by KOLANICH** [comment]
OK, just place it somewhere where it'd be easy for users to find it.

BTW, the issue would have been solved if the functionality of this script was a part of the tool itself. There is a yet another proxy doing the same thing, which is also in go, and it has parsing of wireguard configs, but doesn't have socks support, you may want to join that project and increase the bus factor.

**Comment by zhsj** [comment]
I update docs about the options compared to wg configuration file.

https://github.com/zhsj/wghttp/commit/b7740d309695dccabc42cfe65b3628eba45f4aac

**Comment by KOLANICH** [comment]
The addition to docs is good, but it doesn't solve the usability issue: users download the wireguard config files from the services and want to use them as they are, not to mess manually with command line and shell scripts.

**Comment by zhsj** [comment]
> users download the wireguard config files from the services and want to use them as they are

It's intentional that only command line args and environments are supported. I intend to keep the configuration in one systemd service file, or one `docker run` command.

**Comment by KOLANICH** [comment]
OK, you don't want to put the script anywhere in the repo. I duplicate it here and delete the fork.

```
#!/usr/bin/env python3

import argparse
import re
from pathlib import Path

ipRx = re.compile("User contributions for ((?:\\d+\\.){3}\\d+)")

PORT = 25344


p = argparse.ArgumentParser(description="wghttp starter script")
sp = p.add_subparsers(dest="cmd")
sp.add_parser("ip")

rp = sp.add_parser("run")
rp.add_argument("cfg", help="Path to config file", type=Path)

rp = sp.add_parser("emit")
rp.add_argument("cfg", help="Path to config file", type=Path)


def getIP(port: int) -> str:
	try:
		import httpx as http
	except ImportError:
		import requests as http

	return ipRx.search(
		http.get(
			"https://en.wikipedia.org/wiki/Special:MyContributions",
			proxies={
				"https://": "socks5://localhost:" + str(port),
				"http://": "socks5://localhost:" + str(port),
			},
		).text
	).group(1)


def envDictFromFile(cfgPath: Path):
	import ipaddress

	import wg_conf

	cfg = wg_conf.WireguardConfig(cfgPath)

	d = {}
	d["DNS"] = "8.8.8.8"
	d["LISTEN"] = "localhost:" + str(PORT)
	d["EXIT_MODE"] = "remote"  # local

	d["PRIVATE_KEY"] = cfg.interface["PrivateKey"]
	d["CLIENT_IP"] = str(ipaddress.ip_interface(cfg.interface["Address"]).network_address)

	p = next(iter(cfg.peers.values()))
	d["PEER_KEY"] = p["PublicKey"]
	d["PEER_ENDPOINT"] = p["Endpoint"]

	return d


RUN_COMMAND = ("./wghttp", "-v")


def startProxy(config: Path, port: int) -> int:
	import os
	import subprocess

	os.environ.update(envDictFromFile(config))

	return subprocess.call(RUN_COMMAND)


def emitBashScript(config: Path, port: int):
	print("#!/usr/bin/env bash")
	for k, v in envDictFromFile(config).items():
		print("export", k + "=" + v, ";")

	print(" ".join(RUN_COMMAND))


if __name__ == "__main__":
	args = p.parse_args()
	if args.cmd == "ip":
		print("My IP:", getIP(PORT))
		exit(0)
	elif args.cmd == "run":
		exit(startProxy(args.cfg, PORT))
	elif args.cmd == "emit":
		emitBashScript(args.cfg, PORT)
	else:
		p.print_help()
		exit(1)
```

**Pull request closed without merging**
